---
title: "Opioid Prescription Trends"
author: "Saransh Rakshak"
output: html_document
date: "Due: October 21, 2024"
---

```{r setup}
library(dplyr)
library(ggplot2)
```

<br>

# Part 1. Data Selection and Cleaning

### Perscription Data

**Our data regarding opioid prescriptions is provided by the Centers for Medicare and Medicaid Services (CMS).**

The raw data can be accessed here: https://data.cms.gov/summary-statistics-on-use-and-payments/medicare-medicaid-opioid-prescribing-rates/medicare-part-d-opioid-prescribing-rates-by-geography

**Original Data Information**

    Provided By: CMS
    Contact Email: medicareproviderdata@cms.hhs.gov
    Bureau Code: 009.38
    Program Code: 009.000
    Last Updated: February 8, 2021
    Number of Rows: 1,204,935
    Number of Columns: 11


**Our data from CMS is assigned to the variable *scripts*.** The *scripts* dataframe contains the following columns:

    - NPI: National Provider Identifier for Doctor Identification.
    - last_name, first_name: Prescribing Doctor's last and first name.
    - zip_code: Zip code of prescriber.
    - state: State of prescriber.
    - doc_spec: Specialty of Doctor (ex. Anesthesiology, Internal Medicine, Dentist, etc).
    - tot_presc_cnt: Total amount of prescriptions by the doctor (inclusive of non-opioids).
    - op_cnt: Amount of opioid prescriptions by the doctor.
    - op_rate: Changes in the amount of opioid prescriptions over time by the doctor.
    - LA_op_cnt: Amount of Long-Acting opioid prescriptions by the doctor.
    - LA_op_rate: Changes in the amount of Long-Acting opioid prescriptions over time by the doctor.

Our *scripts* dataframe is also cleaned for easier analysis. Cleaning involves:

    1. Removing information reguarding prescribers NPI, first, and last name for privacy.
    2. Removing data for providers who have not prescibed any opioids, they will not be relavent to our analysis.
    3. Replacing NA values in LA_op_cnt and LA_op_rate with 0.

```{R}
scripts <- read.csv("data/op_2021_data.csv")
scripts <- scripts %>%
  rename(last_name = NPPES.Provider.Last.Name,
         first_name = NPPES.Provider.First.Name,
         zip_code = NPPES.Provider.ZIP.Code,
         state = NPPES.Provider.State,
         doc_spec = Specialty.Description,
         tot_presc_cnt = Total.Claim.Count,
         op_cnt =  Opioid.Claim.Count,
         op_rate = Opioid.Prescribing.Rate,
         LA_op_cnt = Long.Acting.Opioid.Claim.Count,
         LA_op_rate = Long.Acting.Opioid.Prescribing.Rate)

# 1. Selecting relevant columns
scripts <- scripts %>%
  select(zip_code, state, doc_spec, tot_presc_cnt, op_cnt, op_rate, LA_op_cnt, LA_op_rate)

# 2. Removing doctors who have not prescribed any opioids
scripts <- scripts %>%
  filter(op_cnt > 0 | LA_op_cnt > 0)

# 3. Replacing NA values in LA_op_cnt and LA_op_rate with 0
scripts$LA_op_cnt[is.na(scripts$LA_op_cnt)] <- 0
scripts$LA_op_rate[is.na(scripts$LA_op_rate)] <- 0

# Turning double LA_op_cnt to int
scripts$LA_op_cnt <- as.integer(scripts$LA_op_cnt)

glimpse(scripts)
summary(scripts)
```


<br>

### Income Data

**Our data regarding average incomes in different area codes is provided by the Internal Revenue Service (IRS).**

The raw data can be accessed here: https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-statistics-2016-zip-code-data-soi

**I will be using a semi-cleaned version of this IRS data, created by Jon Loyens and posted publicly on data.world.** 

The semi-cleaned data can be accessed here: https://data.world/jonloyens/irs-income-by-zip-code

### Original Data Information

    Provided By: Jon Loyens
    Contact Address: @jonloyens (twitter)
    Last Updated: June 16, 2016
    Number of Rows: 27,790
    Number of Columns: 11
    

**Our data from the IRS is assigned to the variable *income*.** 

The raw dataset from the IRS contains 147 columns and from that our cleaned Loyens dataset contains 11 columns.
Our income dataframe will only use three of those columns. The *income* dataframe contains the following columns:

    - state: The state the zip code is located in.
    - zip_code: Zipcode.
    - zip_avg_income: Average income for a certain zip_code.
    

Our *income* dataframe is also further cleaned for easier analysis. Cleaning involves:

    1. Selecting only the relavent columns of state, zip_code, and zip_avg_income.
    2. Increasing zip_avg_income by a factor of 1000 to get full income values.
    3. Removing rows where zip_code does not have 5 digits, as these are not valid zip codes.
    3. Removing rows where zip_code equals 99999, as these are "other" areas such as a single building or non-residential zip.

```{R}
income <- read.csv("data/IRSIncomeByZipCode.csv")
income <- income %>% 
  rename(state = STATE,
         zip_code = ZIPCODE,
         zip_avg_income = `Avg.total.income`)

# 1. Selecting relevant columns
income <- income %>%
  select(state, zip_code, zip_avg_income)

# 2. Increasing zip_avg_income by a factor of 1000 to get full income values
income$zip_avg_income <- income$zip_avg_income * 1000

# 3. Removing rows where zip_code does not have 5 digits or 99999 zip codes
income <- income %>%
  filter(nchar(as.character(zip_code)) == 5) %>%
  filter(zip_code != 99999)

glimpse(income)
summary(income)
```


### Merging the two dataframes.

```{R}
# Merging by zip_code and state
merged <- scripts %>%
  left_join(income, by = c("state", "zip_code"))

head(merged)
```


We will begin the analysis by looking at opioid prescription types. The two types of opioid prescriptions are regular acting (op_cnt, op_rate) and Long Acting (LA_op_cnt, LA_op_rate). From Figure 1, we can see that regular acting opioids are prescribed far more often than Long Acting. 


```{R}
total_prescribed <- merged %>%
  summarise(total_op_cnt = sum(op_cnt, na.rm = TRUE),
            total_LA_cnt = sum(LA_op_cnt, na.rm = TRUE))

total_prescribed
```


